packages:
  - '.'
onlyBuiltDependencies:
  - '@swc/core'
  - less
  - protobufjs
patchedDependencies:
  postcss-pxtransform@4.2.0: patches/postcss-pxtransform@4.2.0.patch
  postcss-pxtransform@4.2.1: patches/postcss-pxtransform@4.2.1.patch
